[tool.poetry]
name = "cmnd-lite"
version = "0.0.1"
description = ""
homepage = "https://github.com/datakurre/cmnd-lite/"
authors = ["Asko Soukka <asko.soukka@iki.fi>"]
license = "MIT"
readme = "README.md"
packages = [
  { include = "importer.py" }
]

[tool.poetry.scripts]
importer = "importer:main"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
redis = "^4.5.1"
datasette-graphql = "^2.1.2"
datasette = "^0.64.2"
apsw = "3.39.4.0"
datasette-pretty-json = "^0.2.2"
datasette-dashboards = "^0.3.0"
lxml = "^4.9.2"
setuptools = "^67.6.1"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
twine = "^4.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
